### PR TITLE
Handle multiple linux distribution

### PR DESCRIPTION
**Pull request by bew**
not tested.. but everything should work properly

### CODE REVIEW

**Comment by kayofeld** [comment]
I prefer merging only if it was tested before.
Nice job though ! I'll test it when i'll have more time

**Comment by bew** [comment]
Maybe you can merge in a branch, then test, and if it's ok, merge the branch to master (and delete the branch)

**Comment by kayofeld** [comment]
I am beginning the testing today, sorry for the delay.
New test branch created

**Comment by bew** [comment]
Finally :)

**Pull request closed without merging**
